Numpy: package for multidimensioal array


In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,3,2,4])
arr

array([1, 3, 2, 4])

In [5]:
list_of_list=[[1,2,3],[5,6,7],[8,9,10]]
np.array(list_of_list)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
rand_array=np.random.randint(1,10,50)
rand_array

array([5, 4, 2, 1, 4, 8, 4, 9, 9, 4, 6, 2, 3, 3, 4, 7, 8, 8, 7, 8, 4, 3,
       8, 9, 5, 6, 3, 7, 4, 2, 5, 5, 7, 5, 5, 5, 1, 9, 1, 5, 6, 1, 7, 3,
       4, 6, 5, 7, 9, 4])

In [11]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [12]:
rand_array.max()

9

In [13]:
rand_array.argmax()

7

In [20]:
a1=np.eye(5)
a1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
a1.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
a=np.random.rand(2,3)
a

array([[0.22937003, 0.87274884, 0.79187031],
       [0.46062161, 0.55228567, 0.68875284]])

In [24]:
a.T

array([[0.22937003, 0.46062161],
       [0.87274884, 0.55228567],
       [0.79187031, 0.68875284]])

In [25]:
sample_array=np.arange(10,25)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
sample_array[2:5]

array([12, 13, 14])

sample_array[4]=1038379
sample_array

In [28]:
sample_array[0:8]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [29]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [31]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

Two Dimensional array

In [34]:
import numpy as np

In [35]:
sample_matrix=np.array([[45,65,34],[2,56,90],[98,67,78]])
sample_matrix

array([[45, 65, 34],
       [ 2, 56, 90],
       [98, 67, 78]])

In [36]:
sample_matrix[1,2]

90

In [37]:
sample_matrix[2,0]

98

In [39]:
sample_matrix[1,:]

array([ 2, 56, 90])

In [40]:
sample_matrix[2]

array([98, 67, 78])

In [41]:
sample_matrix[:,1]

array([65, 56, 67])

In [44]:
sample_matrix[:,(2,1,0)]

array([[34, 65, 45],
       [90, 56,  2],
       [78, 67, 98]])

selection techinques

In [45]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [46]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [47]:
np.exp(sample_array) # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [48]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [49]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [50]:
np.max(sample_array)

19

In [51]:
np.min(sample_array)

1

In [52]:
np.argmin(sample_array)

0

In [53]:
np.argmax(sample_array)

18

In [54]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [55]:
np.std(sample_array)

5.477225575051661

In [56]:
np.var(sample_array)

30.0

In [57]:
np.mean(sample_array)

10.0

In [58]:
array=np.random.randn(3,4)
array

array([[-0.76997239,  0.28616255, -1.50358509,  2.06853341],
       [ 0.03728873, -0.05300407,  0.45018352, -1.07009206],
       [ 0.21417827,  1.24408589, -0.47520353,  0.44125431]])

In [60]:
np.round(array,decimals=3)

array([[-0.77 ,  0.286, -1.504,  2.069],
       [ 0.037, -0.053,  0.45 , -1.07 ],
       [ 0.214,  1.244, -0.475,  0.441]])

In [62]:
sports=np.array(['golf','cricket','fball','vollyball'])
np.unique(sports)

array(['cricket', 'fball', 'golf', 'vollyball'], dtype='<U9')

In [63]:
### pandas


In [ ]:
import pandas as pd
import numpy as np

Pandas dataframe and indexing

In [66]:
import pandas as pd

In [70]:
sports1=pd.Series([1,2,3,4,5],index=['cricket','football','basketball','hockey','golf'])
sports1

cricket       1
football      2
basketball    3
hockey        4
golf          5
dtype: int64

In [68]:
sports1['football']

2

In [72]:
sports1['hockey']

4

In [73]:
sports2=pd.Series([11,3,6,9],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     3
baseball     6
golf         9
dtype: int64

In [74]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       5.0
golf          14.0
hockey         NaN
dtype: float64

In [83]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.992983  0.578690  0.430623  0.155333  0.725295
B  0.021651  0.470826  0.965961  0.208110  0.446302
C  0.559558  0.584919  0.953269  0.396771  0.656575
D  0.652546  0.042580  0.122091  0.610044  0.444672
E  0.180697  0.903626  0.287775  0.812141  0.827181
F  0.553774  0.083014  0.798790  0.469245  0.909826
G  0.869050  0.339546  0.206065  0.079043  0.888357
H  0.245749  0.814963  0.521865  0.758518  0.507450

In [84]:
df1['Score2']

A    0.578690
B    0.470826
C    0.584919
D    0.042580
E    0.903626
F    0.083014
G    0.339546
H    0.814963
Name: Score2, dtype: float64

In [85]:
df1['Score5']

A    0.725295
B    0.446302
C    0.656575
D    0.444672
E    0.827181
F    0.909826
G    0.888357
H    0.507450
Name: Score5, dtype: float64

In [88]:
df1[['Score2','Score2']]

Score2    Score2
A  0.578690  0.578690
B  0.470826  0.470826
C  0.584919  0.584919
D  0.042580  0.042580
E  0.903626  0.903626
F  0.083014  0.083014
G  0.339546  0.339546
H  0.814963  0.814963

In [90]:
df1['Score6']=df1['Score1']+df1['Score2']
df1['Score6']

A    1.571672
B    0.492477
C    1.144477
D    0.695126
E    1.084323
F    0.636788
G    1.208596
H    1.060712
Name: Score6, dtype: float64

In [91]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.992983  0.578690  0.430623  0.155333  0.725295  1.571672
B  0.021651  0.470826  0.965961  0.208110  0.446302  0.492477
C  0.559558  0.584919  0.953269  0.396771  0.656575  1.144477
D  0.652546  0.042580  0.122091  0.610044  0.444672  0.695126
E  0.180697  0.903626  0.287775  0.812141  0.827181  1.084323
F  0.553774  0.083014  0.798790  0.469245  0.909826  0.636788
G  0.869050  0.339546  0.206065  0.079043  0.888357  1.208596
H  0.245749  0.814963  0.521865  0.758518  0.507450  1.060712

In [6]:
import pandas as pd

In [10]:
 df2={'ID':['131','132','133','134','135'],'Name':['NIDHI','NIKHIL','NILANSHU','NIRMAL','NISHA'],'Profit':[30,56,89,60,50]}
df=pd.DataFrame(df2)
df

ID      Name  Profit
0  131     NIDHI      30
1  132    NIKHIL      56
2  133  NILANSHU      89
3  134    NIRMAL      60
4  135     NISHA      50

In [11]:
df['ID']

0    131
1    132
2    133
3    134
4    135
Name: ID, dtype: object

In [13]:
df['Profit']

0    30
1    56
2    89
3    60
4    50
Name: Profit, dtype: int64

In [16]:
df[['Name','ID']]

Name   ID
0     NIDHI  131
1    NIKHIL  132
2  NILANSHU  133
3    NIRMAL  134
4     NISHA  135

In [23]:
df=df.drop('ID',axis=2)
df

ValueError: No axis named 2 for object type DataFrame

In [19]:
df.drop(3)

Name  Profit
0     NIDHI      30
1    NIKHIL      56
2  NILANSHU      89
4     NISHA      50